name: 24/7 Live Stream (Pro Anti-Bot)

on:
  schedule:
    - cron: '0 */6 * * *' # Restart every 6 hours
  workflow_dispatch:

jobs:
  streaming_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start Stream
        env:
          STREAM_URL: ${{ secrets.STREAM_URL }}
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          while true; do

            echo "Generating new shuffled playlist..."
            rm -f playlist.txt

            for f in ./music/*.mp3; do
              echo "file '$PWD/$f'" >> playlist.txt
            done

            shuf playlist.txt -o playlist.txt

            echo "Starting FFmpeg stream..."

            ffmpeg -re -stream_loop -1 -i "test1-2026.mp4" \
            -f concat -safe 0 -i playlist.txt \
            -c:v libx264 -preset ultrafast -tune zerolatency \
            -profile:v high -level 4.1 \
            -b:v 4000k -minrate 4000k -maxrate 4000k -bufsize 8000k -nal-hrd cbr \
            -c:a aac -b:a 128k -ar 44100 \
            -map 0:v -map 1:a -fflags +genpts \
            -f flv "$STREAM_URL/$STREAM_KEY"

            echo "FFmpeg stopped. Restarting with new shuffle..."

          done